<script lang="ts">
	import { tick } from 'svelte';
	import { fade } from 'svelte/transition';
	import WeeklyBarChart from '$lib/components/WeeklyBarChart.svelte';

	export let data;

	let searchQuery = '';
	let matches: string[] = [];
	let isTruncated = false;
	let totalMatches = 0;
	let wasEmpty = true;

	$: {
		if (searchQuery.length >= 2 && data?.speciesLocations) {
			const lowerQuery = searchQuery.toLowerCase();
			const allMatches = Object.keys(data.speciesLocations)
				.filter((name) => {
					if (name.toLowerCase().includes(lowerQuery)) return true;
					const meta = data.speciesSearchData?.[name];
					if (meta) {
						if (meta.sciName?.toLowerCase().includes(lowerQuery)) return true;
						if (meta.codes?.some((c: string) => c.toLowerCase().includes(lowerQuery))) return true;
					}
					return false;
				})
				.sort();
			totalMatches = allMatches.length;
			matches = allMatches.slice(0, 10); // Show top 10
			isTruncated = allMatches.length > 10;

			// Scroll if we have new results and weren't showing any before
			if (matches.length > 0 && wasEmpty) {
				wasEmpty = false;
				scrollToResults();
			}
		} else {
			matches = [];
			isTruncated = false;
			totalMatches = 0;
			wasEmpty = true;
		}
	}

	async function scrollToResults() {
		await tick(); // Wait for DOM update
		const el = document.getElementById('search-results-anchor');
		if (el) {
			el.scrollIntoView({ behavior: 'smooth' });
		}
	}

	let showBackToTop = false;
	let activeSeasonInfo: string | null = null;
	let innerHeight = 0;
	let scrollY = 0;

	$: showBackToTop = scrollY > innerHeight * 0.5;

	function scrollToTop() {
		window.scrollTo({ top: 0, behavior: 'smooth' });
	}
</script>

<svelte:window bind:scrollY bind:innerHeight />

<svelte:head>
	<title>Kerakis // Birding Guide</title>
</svelte:head>

<header class="mb-6 text-sm text-black dark:text-white" aria-label="Breadcrumb">
	<span class="font-bold">Birding Guide</span>
	<span class="text-accent mx-2">—</span>
	<span>
		A guide to birding in Knox County, including top spots, seasonal highlights, and a search tool
		for finding our feathered friends.
	</span>
</header>

<!-- Quick Navigation -->
<nav
	class="border-accent sticky top-6 z-10 mx-auto mb-8 w-fit max-w-[95%] border bg-white/90 px-6 py-2.5 shadow-sm backdrop-blur-md dark:bg-zinc-900/90"
>
	<ul class="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm font-medium">
		<li>
			<a href="#intro" class="hover:text-accent transition-colors">Intro</a>
		</li>
		<li>
			<a href="#methodology" class="hover:text-accent transition-colors">Methodology</a>
		</li>
		<li>
			<a href="#top-locations" class="hover:text-accent transition-colors">Top Locations</a>
		</li>
		<li>
			<a href="#seasonal-highlights" class="hover:text-accent transition-colors">By Season</a>
		</li>
		<li>
			<a href="#target-species" class="hover:text-accent transition-colors">Target Species</a>
		</li>
	</ul>
</nav>

<div class="m-auto mt-8 w-11/12 space-y-16">
	<!-- Introduction Section -->
	<section class="scroll-mt-24 space-y-4" id="intro">
		<h2 class="text-accent text-3xl font-bold">Welcome to Birding in Knox County</h2>
		<div class="space-y-3 text-lg leading-relaxed">
			<p>
				Knox County is a great birding location with diverse habitats and over
				{data?.stats?.totalSpecies} species recorded in the last 10 years. From The Cove to Seven Islands,
				there are hotspots for every season. Use this guide to discover where to find your target birds
				and explore the rich avian diversity of our county.
			</p>
		</div>
	</section>

	<!-- Methodology / Behind the Scenes -->
	<section class="scroll-mt-24 rounded-lg bg-gray-50 p-6 dark:bg-zinc-800/50" id="methodology">
		<h2 class="text-accent mb-4 text-2xl font-bold">Behind the Birding Data</h2>
		<div class="space-y-4 text-base">
			<p>
				The top birding locations list below is generated by analyzing eBird checklists from Knox
				County from the last 10 years, and ordered by the number of species recorded at each
				hotspot.
			</p>
			<p>
				The seasonal lists below are generated by analyzing eBird checklists from Knox County from
				the last 10 years. Birds are categorized into two distinct groups to help you find what
				makes each location special:
			</p>
			<div class="grid gap-8 md:grid-cols-2">
				<div>
					<h3 class="mb-2 text-lg font-bold">Notable Species</h3>
					<p class="mb-2 text-sm text-gray-700 dark:text-gray-300">
						These are the birds that are a "speciality" of a hotspot. To be listed, a species must
						be:
					</p>
					<ul class="list-disc space-y-1 pl-5 text-sm text-gray-600 dark:text-gray-400">
						<li>Seen <strong>1.5x more frequently</strong> here than the regional average.</li>
						<li>Present in <strong>at least 2 separate years</strong>.</li>
						<li>Available in <strong>>30%</strong> of years with data.</li>
					</ul>
					<p class="mt-2 text-xs text-gray-500 italic">
						* This excludes "one-hit wonders" (like a rare bird that stayed for a week one time) to
						ensure you can more reliably expect to find these birds in season.
					</p>
				</div>
				<div>
					<h3 class="mb-2 text-lg font-bold">Regional Rarities</h3>
					<p class="mb-2 text-sm text-gray-700 dark:text-gray-300">
						These are unusual and exciting finds for the county.
					</p>
					<ul class="list-disc space-y-1 pl-5 text-sm text-gray-600 dark:text-gray-400">
						<li>Present on less than <strong>1%</strong> of all checklists in the region.</li>
						<li>Often one-time sightings or very localized specialties.</li>
					</ul>
					<p class="mt-2 text-xs text-gray-500 italic">
						* Shown with their last seen year so you know if it's a recent record or a historical
						rarity.
					</p>
				</div>
			</div>
			<div class="mt-8 border-t border-gray-200 pt-6 dark:border-gray-700">
				<h3 class="mb-3 text-lg font-bold text-gray-800 dark:text-gray-200">About the Data</h3>
				<ul class="list-disc space-y-2 pl-5 text-sm text-gray-600 dark:text-gray-400">
					<li>
						<strong>Citation:</strong>
						eBird Basic Dataset. Version: EBD_relJan-2026. Cornell Lab of Ornithology, Ithaca, New York.
						Jan 2026.
					</li>
					<li>
						<strong>Data freshness:</strong>
						Data is current as of January 2026.
					</li>
					<li>
						<strong>Exclusions:</strong> Locations marked as "No Access", "Restricted Access", or "Private
						Property" are excluded.
					</li>
					<li>
						<strong>New Hotspots:</strong> Hotspots with less than 2 years of data may rank lower or show
						fewer notable species until reliability is established.
					</li>
					<li>
						<strong>Ranking Logic:</strong> Hotspots are ranked by a combination of unique species presence
						(how unique the birds are there relative to the rest of the county) and overall diversity.
						The "uniqueness" score is capped for any single species to prevent one rare bird from skewing
						the results. This ensures the top spots are consistently reliable.
					</li>
				</ul>
			</div>
		</div>
	</section>

	<!-- Top Birding Locations -->
	<section class="scroll-mt-24 space-y-6" id="top-locations">
		<h2 class="text-accent text-3xl font-bold">Top Overall Birding Locations</h2>
		<p class="text-base text-black dark:text-white">
			Use these hotspots to find the richest species diversity overall. Be sure to compare with the
			seasonal lists below to find out which locations are best for finding migrants alongside
			year-round residents.
		</p>
		<div class="grid gap-6 sm:grid-cols-1 md:grid-cols-2">
			{#if data?.hotspots && data.hotspots.length > 0}
				{#each data.hotspots as hotspot (hotspot.id)}
					<div
						class="hover:border-accent min-h-32 border p-6 transition-colors duration-200 ease-in-out"
					>
						<h3 class="mb-3 text-2xl font-bold">{hotspot.name}</h3>
						<div class="space-y-2 text-base">
							<p>
								<span class="font-semibold">Species Recorded:</span>
								{hotspot.speciesCount}
							</p>
							<p>
								<span class="font-semibold">Coordinates:</span>
								<a
									href="https://www.google.com/maps/search/?api=1&query={hotspot.latitude},{hotspot.longitude}"
									target="_blank"
									rel="noreferrer"
									class="text-accent hover:underline"
									title="View on Google Maps"
								>
									{hotspot.latitude.toFixed(4)}, {hotspot.longitude.toFixed(4)}
								</a>
							</p>
							<p class="mt-3 text-sm">
								<a
									href="https://ebird.org/hotspot/{hotspot.id}"
									target="_blank"
									rel="noreferrer"
									class="text-accent hover:underline">View on eBird →</a
								>
							</p>
						</div>
					</div>
				{/each}
			{:else}
				<p class="col-span-full text-base">Loading hotspot data...</p>
			{/if}
		</div>
	</section>

	<!-- Seasonal Highlights -->
	<section class="scroll-mt-24 space-y-6" id="seasonal-highlights">
		<h2 class="text-accent text-3xl font-bold">Best Hotspots by Season</h2>
		<p class="text-base text-black dark:text-white">
			Use these hotspots to find seasonal migrants. Each hotspot lists its most notable species for
			that season, along with any rarities that have been spotted there.
		</p>
		<div class="space-y-8">
			{#each ['spring', 'summer', 'fall', 'winter'] as seasonKey}
				{@const typedSeason = seasonKey as 'spring' | 'summer' | 'fall' | 'winter'}
				{@const seasonData = data?.seasonalHotspots?.[typedSeason] ?? []}
				{@const seasonDates = {
					spring: 'March - May',
					summer: 'June - August',
					fall: 'September - November',
					winter: 'December - February'
				}[typedSeason]}
				<div>
					<div
						class="mb-4 flex items-center justify-between border-b border-gray-200 pb-2 dark:border-gray-700"
					>
						<h3 class="text-accent text-2xl font-bold capitalize">
							{seasonKey}
							<span class="ml-2 text-lg font-normal text-gray-500 dark:text-gray-400"
								>({seasonDates})</span
							>
						</h3>
						<div class="relative">
							<button
								class="flex h-4 w-4 items-center justify-center rounded-full bg-gray-200 font-serif text-[10px] font-bold text-gray-500 italic transition-all hover:bg-gray-300 hover:text-gray-700 focus:bg-gray-300 focus:text-gray-700 focus:outline-none dark:bg-zinc-700 dark:text-zinc-400 dark:hover:bg-zinc-600 dark:hover:text-zinc-200 dark:focus:bg-zinc-600 dark:focus:text-zinc-200"
								on:mouseenter={() => (activeSeasonInfo = seasonKey)}
								on:mouseleave={(e) => {
									activeSeasonInfo = null;
									e.currentTarget.blur();
								}}
								on:focus={() => (activeSeasonInfo = seasonKey)}
								on:blur={() => (activeSeasonInfo = null)}
								on:click={(e) => e.currentTarget.focus()}
								aria-label="How to read seasonal hotspots"
							>
								i
							</button>
							{#if activeSeasonInfo === seasonKey}
								<div
									transition:fade={{ duration: 150 }}
									class="absolute top-full right-0 z-30 mt-2 w-64 rounded bg-white p-4 shadow-xl ring-1 ring-black/5 dark:bg-zinc-800 dark:ring-white/10"
								>
									<div class="space-y-3 text-xs text-gray-600 dark:text-gray-300">
										<p>
											<strong class="text-gray-900 dark:text-white">Seasonal Species:</strong>
											These are the number of birds that you can reasonably expect to see at this hotspot
											during this season.
										</p>
										<p>
											<strong class="text-gray-900 dark:text-white"
												>Notable Species (X/Y years):</strong
											>
											Indicates consistency. "Seen in 8/10 years" means the species was recorded during
											this season in 8 of the last 10 years. The total years (Y) may vary if a hotspot
											lacks data for some years or if the current season hasn't occurred yet.
										</p>
									</div>
								</div>
							{/if}
						</div>
					</div>
					<div class="grid gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
						{#each seasonData as hotspot (hotspot.hotspotId)}
							<div
								class="hover:border-accent min-h-32 border p-4 transition-colors duration-200 ease-in-out"
							>
								<h4 class="mb-2 font-bold">
									<a
										href="https://www.google.com/maps/search/?api=1&query={hotspot.latitude},{hotspot.longitude}"
										target="_blank"
										rel="noreferrer"
										class="hover:text-accent hover:underline"
										title="View on Google Maps"
									>
										{hotspot.hotspotName}
									</a>
								</h4>
								<p class="mb-3 text-sm">
									<span class="font-semibold">Seasonal Species:</span>
									{hotspot.seasonalSpeciesCount}
								</p>
								<div class="space-y-1 text-xs">
									<p class="font-semibold">Notable Species:</p>
									<ul class="space-y-0.5 pl-2">
										{#each hotspot.notableSpecies as species}
											<li class="relative">
												<button
													class="group block w-full cursor-help truncate text-left focus:outline-none"
													on:mouseleave={(e) => e.currentTarget.blur()}
													on:click={(e) => e.currentTarget.focus()}
												>
													<span class="block truncate">• {species.name}</span>
													<!-- Tooltip -->
													<div
														class="invisible absolute bottom-full left-1/2 z-20 mb-1 w-max min-w-37.5 -translate-x-1/2 rounded bg-gray-900 px-2 py-1 text-center text-xs text-white opacity-0 shadow-lg transition-all group-hover:visible group-hover:opacity-100 group-focus:visible group-focus:opacity-100"
													>
														{species.name}
														<br />
														<span class="text-gray-300"
															>(Seen in {species.yearsPresent}/{species.yearsTotal} years)</span
														>
														<!-- Triangle -->
														<div
															class="absolute top-full left-1/2 -mt-px -ml-1 border-4 border-transparent border-t-gray-900"
														></div>
													</div>
												</button>
											</li>
										{/each}
									</ul>
								</div>

								{#if hotspot.rareSpecies && hotspot.rareSpecies.length > 0}
									<div class="mt-2 space-y-1 text-xs">
										<p class="font-semibold">Regional Rarities:</p>
										<ul class="space-y-0.5 pl-2 text-gray-600 italic dark:text-gray-400">
											{#each hotspot.rareSpecies as species}
												<li class="relative">
													<button
														class="group block w-full cursor-help truncate text-left focus:outline-none"
														on:mouseleave={(e) => e.currentTarget.blur()}
														on:click={(e) => e.currentTarget.focus()}
													>
														<span class="block truncate">
															• {species.name}
															<span class="text-[10px] not-italic opacity-70"
																>({species.lastSeenYear})</span
															>
														</span>
														<!-- Tooltip -->
														<div
															class="invisible absolute bottom-full left-1/2 z-20 mb-1 w-max min-w-50 -translate-x-1/2 rounded bg-gray-900 px-2 py-1 text-center text-xs text-white not-italic opacity-0 shadow-lg transition-all group-hover:visible group-hover:opacity-100 group-focus:visible group-focus:opacity-100"
														>
															{species.name}
															<br />
															<span class="text-gray-300"
																>(Observations: {species.obsCount}, Last Observed: {species.lastSeenYear})</span
															>
															<!-- Triangle -->
															<div
																class="absolute top-full left-1/2 -mt-px -ml-1 border-4 border-transparent border-t-gray-900"
															></div>
														</div>
													</button>
												</li>
											{/each}
										</ul>
									</div>
								{/if}
								<p class="mt-3 text-xs">
									<a
										href="https://ebird.org/hotspot/{hotspot.hotspotId}"
										target="_blank"
										rel="noreferrer"
										class="text-accent hover:underline">View on eBird →</a
									>
								</p>
							</div>
						{:else}
							<p class="col-span-full text-sm text-gray-400">
								No seasonal hotspots found for this period. Try again later as more observation data
								is collected.
							</p>
						{/each}
					</div>
				</div>
			{/each}
		</div>
	</section>

	<!-- Target Species -->
	<section class="scroll-mt-20 space-y-6" id="target-species">
		<h2 class="text-accent text-3xl font-bold">Target Species</h2>
		<p class="text-base text-black dark:text-white">
			Looking for a specific bird? Search below to find the top hotspots for any species recorded in
			Knox County by season, based on frequency of observation.
		</p>

		<div class="relative max-w-xl">
			<input
				type="text"
				bind:value={searchQuery}
				placeholder="Search for a species..."
				class="w-full border border-black p-4 text-lg transition-all outline-none placeholder:text-gray-400 focus:border-red-500 focus:ring-1 focus:ring-red-500 dark:border-white dark:focus:border-red-500"
			/>
			<div class="absolute top-1/2 right-4 -translate-y-1/2 text-gray-400">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					width="20"
					height="20"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<circle cx="10" cy="10" r="7" />
					<line x1="21" y1="21" x2="15" y2="15" />
				</svg>
			</div>
		</div>

		<div id="search-results-anchor" class="scroll-mt-24"></div>

		{#if searchQuery.length > 0 && searchQuery.length < 2}
			<p class="text-gray-500 italic">Type at least 2 characters to search...</p>
		{:else if matches.length > 0}
			{#if isTruncated}
				<div class="mb-4 text-sm text-gray-500 dark:text-gray-400">
					Showing the first {matches.length} of {totalMatches} results. Refine your search for more specific
					species.
				</div>
			{/if}
			<div class="space-y-8">
				{#each matches as speciesName (speciesName)}
					{@const speciesData =
						data.speciesLocations &&
						typeof data.speciesLocations === 'object' &&
						speciesName in data.speciesLocations
							? // @ts-ignore
								data.speciesLocations[speciesName]
							: null}
					{@const seasons = speciesData?.seasons}
					{@const code = speciesData?.code}

					<div
						class="hover:border-accent border border-black p-6 shadow-sm transition-colors dark:border-white"
					>
						<div class="mb-6 flex flex-col gap-1">
							<h3 class="text-accent text-2xl font-bold">
								{#if code}
									<a
										href="https://ebird.org/species/{code}/US-TN-093"
										target="_blank"
										rel="noreferrer"
										class="hover:underline"
										title="View {speciesName} on eBird"
									>
										{speciesName}
									</a>
								{:else}
									{speciesName}
								{/if}
							</h3>
							{#if data.speciesSearchData?.[speciesName]}
								{@const meta = data.speciesSearchData[speciesName]}
								<span class="text-sm text-gray-500 italic dark:text-gray-400">
									{meta.sciName}
								</span>
							{/if}
						</div>

						{#if speciesData.weeklyStats}
							<WeeklyBarChart weeklyStats={speciesData.weeklyStats} />
						{/if}

						<div class="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
							{#each ['spring', 'summer', 'fall', 'winter'] as season}
								{@const seasonData = seasons[season]}
								<div class="space-y-3">
									<h4
										class="border-b border-gray-200 pb-1 text-xs font-bold tracking-wider text-gray-500 uppercase dark:border-gray-700 dark:text-gray-400"
									>
										{season}
									</h4>
									{#if seasonData && seasonData.length > 0}
										<ul class="space-y-3 text-sm">
											{#each seasonData as loc}
												<li class="flex flex-col">
													<a
														href="https://ebird.org/hotspot/{loc.id}"
														target="_blank"
														rel="noreferrer"
														class="hover:text-accent font-bold text-gray-900 hover:underline dark:text-gray-100"
													>
														{loc.name}
													</a>
													<span class="text-xs text-gray-500 dark:text-gray-400">
														Seen on {(loc.frequency * 100).toFixed(1)}% of checklists
													</span>
												</li>
											{/each}
										</ul>
									{:else}
										<p class="text-xs text-gray-400 italic">No sufficient data</p>
									{/if}
								</div>
							{/each}
						</div>
					</div>
				{/each}
			</div>
		{:else if searchQuery.length >= 2}
			<p class="text-gray-500 italic">No species found matching "{searchQuery}"</p>
		{/if}
	</section>

	<!-- Tips and Resources -->
	<!--
	<section class="space-y-6">
		<h2 class="text-accent text-3xl font-bold">Tips & Resources</h2>
		<div class="space-y-3 text-lg leading-relaxed">
			<ul class="list-inside list-disc space-y-2">
				// Tips list will go here 
				<li>[Tip or resource]</li>
			</ul>
		</div>
	</section>
	-->
</div>

{#if showBackToTop}
	<button
		on:click={scrollToTop}
		class="text-accent fixed right-6 bottom-6 z-50 rounded-full border border-gray-200 bg-white p-3 shadow-lg transition-colors hover:bg-gray-100 dark:border-zinc-700 dark:bg-zinc-800 dark:hover:bg-zinc-700"
		aria-label="Back to top"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			stroke-linecap="round"
			stroke-linejoin="round"
		>
			<path d="m18 15-6-6-6 6" />
		</svg>
	</button>
{/if}
