<script lang="ts">
	export let data;
</script>

<svelte:head>
	<title>Kerakis // Birding Guide</title>
</svelte:head>

<header class="mb-6 text-sm text-black dark:text-white" aria-label="Breadcrumb">
	<span class="font-bold">Birding Guide</span>
	<span class="text-accent mx-2">—</span>
	<span>
		A guide to birding in Knox County, including top spots, seasonal highlights, and tips for
		finding our feathered friends.
	</span>
</header>

<div class="m-auto mt-8 w-11/12 space-y-12">
	<!-- Introduction Section -->
	<section class="space-y-4">
		<h2 class="text-accent text-3xl font-bold">Welcome to Birding in Knox County</h2>
		<div class="space-y-3 text-lg leading-relaxed">
			<p>
				Knox County is a fantastic birding destination with diverse habitats and over
				{data?.stats?.totalSpecies || '300'} species recorded. From the Great Smoky Mountains to the Tennessee
				River, there's always something new to discover.
			</p>
		</div>
	</section>

	<!-- Top Birding Locations -->
	<section class="space-y-6">
		<h2 class="text-accent text-3xl font-bold">Top Birding Locations</h2>
		<div class="grid gap-6 sm:grid-cols-1 md:grid-cols-2">
			{#if data?.hotspots && data.hotspots.length > 0}
				{#each data.hotspots as hotspot (hotspot.id)}
					<div
						class="hover:border-accent min-h-32 border p-6 transition-colors duration-200 ease-in-out"
					>
						<h3 class="mb-3 text-2xl font-bold">{hotspot.name}</h3>
						<div class="space-y-2 text-base">
							<p>
								<span class="font-semibold">Species Recorded:</span>
								{hotspot.speciesCount}
							</p>
							<p>
								<span class="font-semibold">Coordinates:</span>
								{hotspot.latitude.toFixed(4)}, {hotspot.longitude.toFixed(4)}
							</p>
							<p class="mt-3 text-sm">
								<a
									href="https://ebird.org/hotspot/{hotspot.id}"
									target="_blank"
									rel="noreferrer"
									class="text-accent hover:underline">View on eBird →</a
								>
							</p>
						</div>
					</div>
				{/each}
			{:else}
				<p class="col-span-full text-base">Loading hotspot data...</p>
			{/if}
		</div>
	</section>

	<!-- Methodology / Behind the Scenes -->
	<section class="rounded-lg bg-gray-50 p-6 dark:bg-zinc-800/50">
		<h2 class="text-accent mb-4 text-2xl font-bold">Behind the Birding Data</h2>
		<div class="space-y-4 text-base">
			<p>
				The seasonal lists below are generated by analyzing eBird checklists from Knox County from
				the last 10 years. We categorize birds into two distinct groups to help you find what makes
				each location special:
			</p>
			<div class="grid gap-8 md:grid-cols-2">
				<div>
					<h3 class="mb-2 text-lg font-bold">Notable Species (Reliable)</h3>
					<p class="mb-2 text-sm text-gray-700 dark:text-gray-300">
						These are the birds that "define" a hotspot. To be listed, a species must be:
					</p>
					<ul class="list-disc space-y-1 pl-5 text-sm text-gray-600 dark:text-gray-400">
						<li>Seen <strong>1.5x more frequently</strong> here than the regional average.</li>
						<li>Present in <strong>at least 2 separate years</strong>.</li>
						<li>Available in <strong>>30%</strong> of years with data.</li>
					</ul>
					<p class="mt-2 text-xs text-gray-500 italic">
						* This excludes "one-hit wonders" (like a rare bird that stayed for a week once) to
						ensure you can reliably expect to find these birds in season.
					</p>
				</div>
				<div>
					<h3 class="mb-2 text-lg font-bold">Regional Rarities (Vagrants)</h3>
					<p class="mb-2 text-sm text-gray-700 dark:text-gray-300">
						These are unusual exciting finds for the county.
					</p>
					<ul class="list-disc space-y-1 pl-5 text-sm text-gray-600 dark:text-gray-400">
						<li>Present on less than <strong>1%</strong> of all checklists in the region.</li>
						<li>Often one-time sightings or very localized specialties.</li>
					</ul>
					<p class="mt-2 text-xs text-gray-500 italic">
						* Shown with their last seen year so you know if it's a recent record or a historical
						rarity.
					</p>
				</div>
			</div>
			<p class="mt-4 border-t border-gray-200 pt-4 text-sm dark:border-gray-700">
				<strong>Note:</strong> Newer hotspots with less than 2 years of data may not show "Notable" species
				yet, as we need multiple years to establish reliability.
			</p>
		</div>
	</section>

	<!-- Seasonal Highlights -->
	<section class="space-y-6">
		<h2 class="text-accent text-3xl font-bold">Best Hotspots by Season</h2>
		<p class="text-base text-black dark:text-white">
			These hotspots are best for finding seasonal migrants and species you won't see in other times
			of year. Spring and Fall are prime for warblers, while Winter brings waterfowl.
		</p>
		<div class="space-y-8">
			{#each ['spring', 'summer', 'fall', 'winter'] as seasonKey}
				{@const typedSeason = seasonKey as 'spring' | 'summer' | 'fall' | 'winter'}
				{@const seasonData = data?.seasonalHotspots?.[typedSeason] ?? []}
				<div>
					<h3 class="text-accent mb-4 text-2xl font-bold capitalize">{seasonKey}</h3>
					<div class="grid gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
						{#each seasonData as hotspot (hotspot.hotspotId)}
							<div
								class="hover:border-accent min-h-32 border p-4 transition-colors duration-200 ease-in-out"
							>
								<h4 class="mb-2 font-bold">{hotspot.hotspotName}</h4>
								<p class="mb-3 text-sm">
									<span class="font-semibold">Seasonal Species:</span>
									{hotspot.seasonalSpeciesCount}
								</p>
								<div class="space-y-1 text-xs">
									<p class="font-semibold">Notable Species:</p>
									<ul class="space-y-0.5 pl-2">
										{#each hotspot.notableSpecies as species}
											<li
												class="truncate"
												title="{species.name} (Seen in {species.yearsPresent}/{species.yearsTotal} years)"
											>
												• {species.name}
											</li>
										{/each}
									</ul>
								</div>

								{#if hotspot.rareSpecies && hotspot.rareSpecies.length > 0}
									<div class="mt-2 space-y-1 text-xs">
										<p class="font-semibold">Regional Rarities:</p>
										<ul class="space-y-0.5 pl-2 text-gray-600 italic dark:text-gray-400">
											{#each hotspot.rareSpecies as species}
												<li
													class="truncate"
													title="{species.name} ({species.obsCount} obs, last {species.lastSeenYear})"
												>
													• {species.name}
													<span class="text-[10px] not-italic opacity-70"
														>({species.lastSeenYear})</span
													>
												</li>
											{/each}
										</ul>
									</div>
								{/if}
								<p class="mt-3 text-xs">
									<a
										href="https://ebird.org/hotspot/{hotspot.hotspotId}"
										target="_blank"
										rel="noreferrer"
										class="text-accent hover:underline">View on eBird →</a
									>
								</p>
							</div>
						{:else}
							<p class="col-span-full text-sm text-gray-400">
								No seasonal hotspots found for this period. Try again later as more observation data
								is collected.
							</p>
						{/each}
					</div>
				</div>
			{/each}
		</div>
	</section>

	<!-- Target Species -->
	<section class="space-y-6">
		<h2 class="text-accent text-3xl font-bold">Target Species</h2>
		<div class="space-y-4">
			<!-- Species entries will go here -->
			<div class="hover:border-accent border p-6 transition-colors duration-200 ease-in-out">
				<h3 class="mb-2 text-xl font-bold">[Species Name]</h3>
				<p class="text-base">
					<span class="font-semibold">Where to Find:</span> [Location info]
				</p>
				<p class="text-base">
					<span class="font-semibold">When to Look:</span> [Timing info]
				</p>
				<p class="mt-2 text-base">[Additional notes]</p>
			</div>
		</div>
	</section>

	<!-- Tips and Resources -->
	<section class="space-y-6">
		<h2 class="text-accent text-3xl font-bold">Tips & Resources</h2>
		<div class="space-y-3 text-lg leading-relaxed">
			<ul class="list-inside list-disc space-y-2">
				<!-- Tips list will go here -->
				<li>[Tip or resource]</li>
			</ul>
		</div>
	</section>
</div>
